# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file. See [Conventional Commits](https://www.conventionalcommits.org/) for commit guidelines.\n
"""

body = """
{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}](https://github.com/YOUR_ORG/YOUR_REPO/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**({{commit.scope}})** {% endif %}{% if commit.breaking %}[**breaking**]{% endif %} {{ commit.message | trim }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/YOUR_ORG/YOUR_REPO/commit/{{ commit.id }})) - {{ commit.author.name }}
{% endfor %}
{% endfor %}
"""

footer = """
<!-- generated by git-cliff -->
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

commit_parsers = [
    { message = "\\[skip", skip = true },
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs?", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^style", group = "Style" },
    { message = "^revert", group = "Revert" },
    { message = "^test", group = "Tests" },
    { message = "^chore", group = "Chores" },
    { body = ".*security", group = "Security" },
    { message = ".*", group = "Other" },
]

tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
sort_commits = "oldest"
