name: Release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install tools
      run: ./scripts/install-tools.sh
    - name: Generate changelog
      run: git-cliff -c .gitcliff.toml -o CHANGELOG.md
    - name: Create Release (goreleaser)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goreleaser release --rm-dist
